Part1
MasonSelf/PFMCPP_Project7 pull request #1
Opened 2020-11-03 14:00 UTC by MasonSelf

2020-11-04 05:52 UTC, matkatmusic requested changes

2020-11-04 05:52 UTC, matkatmusic commented on Character.cpp
> +        }
All of this is basically doing the same thing 3 times.   
Use your knowledge of references to create a free function that you can call 3 times.
Also, 
```
a) your stats are restored to their initial value if they are lower than it.
```
emphasis on the `if they are lower than it`.   
your code is currently not checking for that.  
and you're not resetting your stat.  you're resetting the initial value to the current stat value.
- [ ] revise

2020-11-04 05:52 UTC, matkatmusic commented on DefensiveItem.cpp
> +#include "Utility.h"
Don't include what you don't use
- [ ] revise

2020-11-04 05:52 UTC, matkatmusic commented on Dragon.h
> +struct Dragon : public Character
struct is public by default.  no need for this keyword
- [ ] revise

2020-11-04 05:52 UTC, matkatmusic commented on DragonSlayer.h
> +struct DragonSlayer : public Character
struct is public by default.  no need for this keyword
- [ ] revise

2020-11-04 05:52 UTC, matkatmusic commented on Dwarf.h
> +struct Dwarf : public Character
struct is public by default.  no need for this keyword
- [ ] revise

2020-11-04 05:52 UTC, matkatmusic commented on HelpfulItem.h
>  struct HelpfulItem : Item
Don't include what you don't use.  you're including a ton of header files in this file.
- [ ] revise

2020-11-04 05:52 UTC, matkatmusic commented on Paladin.h
> +struct Paladin : public Character
struct is public by default.  no need for this keyword
- [ ] revise

2020-11-04 05:52 UTC, matkatmusic commented on Utility.cpp
> +        chDS->boostAttackDamage(item->getBoost() * 10);
this is not getting the attack damage and multiplying it by the boost. Take a look at the Character member functions available to you.
- [ ] revise

2020-11-04 05:52 UTC, matkatmusic commented on main.cpp
>      std::cout << "\nstart of battle" << std::endl;
Verify that your output matches the expected output **exactly**. 
- [ ] revise

2020-11-09 19:18 UTC, MasonSelf commented on main.cpp
>      std::cout << "\nstart of battle" << std::endl;
I put that in there trying to figure out if main() was even running. I addressed all these revisions, but am still getting "Killed exit status 137" as mentioned last week

2020-11-09 23:40 UTC, matkatmusic requested changes

2020-11-09 23:40 UTC, matkatmusic commented on Character.h
> +    void victoryStatReset( int& currentStat, int& initialStat );
No one else is calling this function.  it does not need to be a member function.
make it a free function in the cpp file.
- [ ] revise

2020-11-09 23:40 UTC, matkatmusic commented on Dragon.cpp
> +Dragon::Dragon( std::string name_, int hitPoints, int armor ) : Character(getHP(), armor, 80), name(name_) {}
`getHP()` is a member function of `Character`.  `Character` hasn't even been fully instantiated yet.  Take a look at the naming convention used by the ctor parameter that is initializing a Character member variable with the same name and follow that convention.
- [ ] revise

2020-11-09 23:40 UTC, matkatmusic commented on DragonSlayer.cpp
> +DragonSlayer::DragonSlayer( std:: string name_, int hitPoints, int armor ) : Character(getHP(), armor, 4 ), name(name_)
- [ ] revise, see above comment.

2020-11-09 23:40 UTC, matkatmusic commented on Dwarf.cpp
> +Dwarf::Dwarf( std::string name_, int hitpoints, int armor ) : Character(getHP(), armor, 4), name(name_)
- [ ] revise, see above comment.

2020-11-09 23:40 UTC, matkatmusic commented on Paladin.cpp
> +Paladin::Paladin( std::string name_, int hitpoints, int armor ) : Character(getHP(), armor, 10), name(name_)
- [ ] revise, see above comment.

2020-11-12 08:00 UTC, matkatmusic approved these changes

2020-11-12 08:00 UTC, merged